### ISSUE TITLE
Cannot Enable On OMV 3

### ISSUE THREAD

**Issue by argon5141** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#11]
Fresh install of 3.2.4 via WebGUI. When I attempt to enable the service (on Save) I get 
: Missing 'required' attribute 'beta'. Any help would be greatly appreciated. Thanks!

**Comment by cptjhmiller** [comment]
This has been reported before and i had tried tp repeat the error on my system but could not.
I have since upgraded to omv3 so will try it again on my main machine.

**Comment by argon5141** [comment]
Thank you!

**Comment by cptjhmiller** [comment]
I have tried but it just works, if I even remove the 'beta' attribute from omv's config it is re-added again.
Have you tried uninstalling then reinstalling?

What settings did you enable before clicking save?

**Comment by argon5141** [comment]
Yes... Uninstalled and reinstalled several times, from gui and command
line. I set the data drive on the enable page since it requires it. Nothing
else. Thanks again for looking into this.

**Comment by cptjhmiller** [comment]
> I set the data drive

There is no option to set the data drive, you sure it's the sabnzbd plugin?

**Comment by argon5141** [comment]
Hi,

I worded that poorly. It sets a backup and restore location:

[image: pasted1]

Hope this is helpful,

Brian

**Comment by cptjhmiller** [comment]
I can't see the image :(

Try this

Uninstall the sabnzbd plugin the run the following
```
cd /tmp
wget --trust-server-names https://bintray.com/openmediavault-plugin-developers/erasmus-testing/download_file?file_path=pool%2Fmain%2Fo%2Fopenmediavault-sabnzbd%2Fopenmediavault-sabnzbd_3.2.4_all.deb
dpkg -i openmediavault-sabnzbd_3.2.4_all.deb;apt-get install -f
rm openmediavault-sabnzbd_3.2.4_all.deb
```
Refresh the omv webui

**Comment by argon5141** [comment]
Thanks... I will give it a shot when I get off work.

**Comment by argon5141** [comment]
Still getting the error. I've attached two screen shots, the first is the SAB settings page you couldn't see earlier, the second is the error.
![settingspage](https://cloud.githubusercontent.com/assets/27627754/25107099/f2e1d0d4-2392-11e7-84d8-f7df9405d245.JPG)
![error](https://cloud.githubusercontent.com/assets/27627754/25107111/ff0d8b3c-2392-11e7-8610-78e8a124e541.JPG)

**Comment by cptjhmiller** [comment]
The 'Backup User Settings' was changed some time ago. The latest version's do not use it as shown in your picture.
Does the plugin section say you have 3.2.4 version installed?

Try running
> rm -f /var/cache/openmediavault/cache.*.json
service openmediavault-engined restart

Then refresh the omv webui

**Comment by argon5141** [comment]
Thank you! That worked. It didn't dawn on me it might be a cache issue.
Anyway, that you again. It is up.. now just to get it configured :)

**Comment by cptjhmiller** [comment]
Good to hear it's work now. Any other issues let me know.
