### ISSUE TITLE
Request for OMV4 compatibility

### ISSUE THREAD

**Issue by GeraldST** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#13]
Any plans for providing a new version for OMV 4.x repo? I like this plugin very much and use it regularily - unfortunately now it is preventing me to update to V4. Kindly let me know if this plugin is still maintained.

Thx, Gerald

**Comment by ryecoaaron** [comment]
The maintainer of this plugin has said he does not want to port this and the other downloader plugins to OMV 4.x in favor of running the service in docker.  Please see this thread: https://forum.openmediavault.org/index.php/Thread/19553-OMV-Docker-plugin-media-server-Plex-PlexPy-Ombi-Libresonic-NZBGet-ruTorrent-Sona/
