### ISSUE TITLE
Failed to execute command 'omv-mkconf sabnzbd getsettings'

### ISSUE THREAD

**Issue by myth384** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#2]
I have successfully installed and configured openmediavault-sabnzbd on Kralizec. Sabnzbd is working well. However I receive the error message shown below when reopening the Sabnzbd module in OMV.
config.xml is not empty as indicated contains a sabnzbd portion.
Reinstalling the plugin did not resolve the issue.

Fout #4000:
exception 'OMVException' with message 'Failed to execute command 'omv-mkconf sabnzbd getsettings': /etc/openmediavault/config.xml:1.1: Document is empty

^
/etc/openmediavault/config.xml:1.1: Start tag expected, '<' not found

^' in /usr/share/openmediavault/engined/rpc/sabnzbd.inc:69
Stack trace:
#0 [internal function]: OMVRpcServiceSabnzbd->getSettings(NULL, Array)
#1 /usr/share/php/openmediavault/rpcservice.inc(125): call_user_func_array(Array, Array)
#2 /usr/share/php/openmediavault/rpc.inc(79): OMVRpcServiceAbstract->callMethod('getSettings', NULL, Array)
#3 /usr/sbin/omv-engined(495): OMVRpc::exec('Sabnzbd', 'getSettings', NULL, Array, 1)
#4 {main}

**Comment by superacrosstheway** [comment]
Experienced the same behavior with the subsonic plugin.

**Comment by Munsio** [comment]
I got the same problem - is there a fix possible?
