### ISSUE TITLE
After restart SSL, error message http port = https port

### ISSUE THREAD

**Issue by arnocs** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#3]
Using openmediavault-sabnzbd-1.0.5, sabnzbd version 0.7.20

When configuring the default http 8080/TCP and https 9090/TCP with SSL enabled.
The access works but after restart of the daemon the http port becomes 9090/TCP 
and generating an error.

I've edited the /etc/init.d/sabnzbd and 
commented (disabling) # OPTIONS="$OPTIONS --server $SERVER"

Leaving the start-up ports from the settings in /home/sabnzbd/.sabnzbd/sabnzbd.ini 

for me this resolved the https problem.

**Comment by cptjhmiller** [comment]
When using https the option --htpps {PORT} should be added to the command startup line. This has been fixed in the next version (yet to be released) as well as being able to configure the https option via the plugin with a simple checkbox to enable/disable.
