### ISSUE TITLE
How do you install openmediavault-sabnzbd?

### ISSUE THREAD

**Issue by erix22** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#4]
Hi,

I'm running OpenmediaVault 2.1.6 (Stone Burner) without problem.
I've just discovered the "OpenmediaVault-Plugin-Developpers" repository. What a lovely choice of addons. But do I install them. Instead of talking about all, let start with "openmediavault-sabnzbd".
So, how do I proceed?

Thanks in advance
Regards
Erix

**Comment by cptjhmiller** [comment]
You need to first install OMVExtras

```
http://forums.openmediavault.org/index.php/Thread/2524-Unofficial-Plugin-Repo-for-0-5-Sardaukar-1-0-Kralizec-2-0-Stoneburner/    
```

Then enable the "download manager" and "download manager testing" repos
openmediavault-sabnzbd will now show in the plugins list.
