### ISSUE TITLE
Sabnzbd 1.0 postinst fails to fetch version

### ISSUE THREAD

**Issue by subzero79** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#5]
The STABLE variable fetches version using 

`wget -q http://sourceforge.net/projects/sabnzbdplus/rss?path=/sabnzbdplus -O - | grep -m1 sabnzbdplus | sed 's#.*\/sabnzbdplus\/\(.*\)\/SAB.*#\1#'`

The updated version of sabznbd rss contains now README no so SAB should be replaced with README now to fix the version grab.

Several users posted problems here http://forums.openmediavault.org/index.php/Thread/13170-Sabnzbd-Plugin-install-error/

**Comment by cptjhmiller** [comment]
Been AFK for a bit so only just seen this, you fixed it in the code already?

**Comment by subzero79** [comment]
Should be OK. We can close.
