### ISSUE TITLE
Fresh install fails on OMV3

### ISSUE THREAD

**Issue by z-vap** [OpenMediaVault-Plugin-Developers/openmediavault-sabnzbd#8]
Here is the output from my initial attempt on OMV3..

Setting up par2 (0.6.11-1) ...
Setting up python-yenc (0.4.0-1) ...
Setting up unzip (6.0-16+deb8u2) ...
Setting up unrar-free (1:0.0.1+cvs20140707-1) ...
update-alternatives: using /usr/bin/unrar-free to provide /usr/bin/unrar (unrar) in auto mode
Setting up openmediavault-sabnzbd (3.2.1) ...
Failed to stop sabnzbd.service: Unit sabnzbd.service not loaded.
dpkg: error processing package openmediavault-sabnzbd (--configure):
 subprocess installed post-installation script returned error exit status 5
Processing triggers for openmediavault (3.0.47) ...
Restarting engine daemon ...
Processing triggers for systemd (215-17+deb8u5) ...
Errors were encountered while processing:
 openmediavault-sabnzbd
Creating index of upgradeable packages ...
Creating index of openmediavault plugins ...

> > > **************\* Error ***************

<<< *************************************

> > > **************\* Error ***************

<<< *************************************

**Comment by z-vap** [comment]
i seem to have been able to finally install this.  I am not sure what happened to start this whole thing.  After doing an `apt-get remove openmediavault-sabnzbd`. i then did an `apt-get clean` and then I actually went to the `/var/cache/archives` place and deleted the `.deb` file.    I also noticed the `/etc/init.d/sabnzbd` file had been there after the uninstall also, so that I deleted.  

Then I attempted a reinstall via the webgui and it worked.  After all this at some point the `backup` plugin installed.  Clearly this was not a smooth operation but i eventually got it installed.  

EDIT: also at some point I got the below error once or twice.  

```
>>> *************** Error ***************
Failed to read from socket: Connection reset by peer
```

**Comment by gurchik** [comment]
This also fails on a fresh install of OMV 2.1 after installing OMV-Extras, enabling the Downloaders repo (not the testing), adding the debian non-free repo manually to `/etc/apt/sources.list`, and manually installing `unrar`.

**Comment by nickdrones** [comment]
I have been having no end of trouble with this as well

**Comment by ryecoaaron** [comment]
The best solution is to move to OMV 4.x and use docker - https://forum.openmediavault.org/index.php/Thread/23005-Installation-and-Setup-Videos-Beginning-Intermediate-and-Advanced/
